spring:
  rsocket:
    server:
      port: 7001
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/chattings
    username: root
    password: pass
  sql:
    init:
      mode: never

server:
  port: 9090